### ISSUE TITLE
List of Glycans

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/playbook-partnership#11]
I would like to replicate the `Gene` definition for glycans. I need a good example and also a list of most common ones for auto-complete. See lines 19 & 20 below. 

https://github.com/biocompute-objects/playbook-partnership/blob/4da80c055407c6199e04f4cf44984fe2d2f8c36d/components/core/input/primitives.ts#L13-L25

**Comment by jeet-vora** [comment]
Here is what you requested

examples: { 
     term: 'G17689DH', 
     set: ['G49108TO' ,'G57321FI' ,'G78059CC' ,'G55220VL' ,'G36191CD' ,'G80966KZ' ,'G84467IZ' ,'G17689DH' ,'G86357DX' ,'G29857RC' ,'G56749GV' ,'G25520XG' ,'G63889NK' ,'G94531EZ' ,'G91365ZQ' ,'G80858MF' ,'G45495MK' ,'G77252PU' ,'G91413ZX' ,'G45359RY' ,'G11041DA' ,'G60230HH' ,'G30159WR' ,'G82348BZ' ,'G57818FI' ,'G08146BT' ,'G18938DW' ,'G53752TA' ,'G79809MM' ,'G96921ZU' ,'G22140GZ' ,'G58667NI' ,'G27919IH' ,'G74859XI' ,'G27844UM' ,'G39213VZ' ,'G16828VN' ,'G14047PA' ,'G22768VO' ,'G42358LZ' ,'G50489VC' ,'G86753CK' ,'G86696LV' ,'G45209NR',], 
   }, 


Please note that these GlyTouCan accessions have no face value they are just accessions with no real meaning like Gene terms.
