### ISSUE TITLE
Redo GlyGen Metanode

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/playbook-partnership#17]
GlyGen metanode needs to be reformatted based on changes to GlyGen API.

**Comment by pmcneely** [comment]
We need protein[set] and glycan[set] (and presumably glycoprotein objects) to implement a prototype workflow.

**Comment by jeet-vora** [comment]
<ins>**Objectives**<ins>

**Objective 1**: From GlyGen we need to implement `Protein`, `Protein Set`, `Glycan` and `Glycan Set` metanode/primitives.

- [ ] Protein
- [ ] Protein Set
- [ ] Glycan
- [ ] Glycan Set

 **Objective 2**: Provide `Gene to Protein details information` on the workflow

Gene to Protein
- [ ]   Protein
- [ ]   Gene Name
- [ ]   Gene Location
- [ ]   UniProtKB ID
- [ ]   UniProtKB Accession
- [ ]   Protein Length
- [ ]   UniProtKB Protein Name
- [ ]   Organism


**Objective 3**: Complete the GlyGen `usecase 12` (https://docs.google.com/presentation/d/1V7cwYVwg7pP2IiykJK31Nji0CHOLMb9O4BzH-zlt-6U/edit#slide=id.g1b434adf814_0_0)

- [ ] Complete usecase 12

**Objective 4**: Complete GlyGen metanode documentation

- [ ] Complete GlyGen metanode documentation

**Objective 5**: Create Glycan and Protein Icons + Set Icons
Glycan - https://github.com/biocompute-objects/playbook-partnership/issues/10#issuecomment-1697815578
Protein -

**Comment by jeet-vora** [comment]
<ins> **Documentation**

GlyGen Metanodes with API information
https://gwu0.sharepoint.com/:p:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B88C94C25-07BA-45FF-807A-129012C19E52%7D&file=GlyGen_Metanodes.pptx&action=edit&mobileredirect=true


<ins> **Repository**

biocompute-objects/playbook-partnership
`https://github.com/biocompute-objects/playbook-partnership`
