### ISSUE TITLE
Documentation in a README for BCO integration

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/playbook-partnership#19]
End-user perspective to be added to the user manual. Why does BCO integration matter and why should a user use it / how should they use it -- i.e. what do they do when they go to the BCO portal. 

This is for this deliverable: Y3.209.1 Produce training materials and documentation to guide users how to interface with the CFDE-WP system: draft materials
To facilitate the use of the CFDE-WP but the broader research community, we will generate training materials that will guide users with how to construct the workflow, publish them, create use cases, and add nodes and links to the system

**Comment by tiwa1154** [comment]
https://docs.google.com/document/d/1sal7CqPKkEjybqiUE2AmS7zYSeRQTM8m4_Gn_nEADlA/edit?usp=sharing

**Comment by tiwa1154** [comment]
Will need some advise regarding creating use cases, add nodes and links to the system
