### ISSUE TITLE
WP builder exploration and report

### ISSUE THREAD

**Issue by tiwa1154** [biocompute-objects/playbook-partnership#21]
explore https://playbook-workflow-builder.cloud/graph/extend and make sure everything works including BCO export

**Comment by tiwa1154** [comment]
BCO export function is not live yet

**Comment by tiwa1154** [comment]
Talked to Hadley, still waiting on Daniel Clarke to finish the BCO export function on their end

**Comment by HadleyKing** [comment]
@u8sand
Is there a status on this? 
I am looking at the production version here: https://playbook-workflow-builder.cloud/

**Comment by u8sand** [comment]
@tiwa1154 @HadleyKing BCO Export feature *is* live (and has been for a long time).

After turning a workflow into a report and saving it, the BCO button allows you to save (download) or publish the BCO on the BCO portal.

![image](https://github.com/biocompute-objects/playbook-partnership/assets/1341861/098c5550-9de1-4052-b535-bb766e8ed883)
![image](https://github.com/biocompute-objects/playbook-partnership/assets/1341861/f5d206bb-e428-4d87-8a1f-448310a9f811)
![image](https://github.com/biocompute-objects/playbook-partnership/assets/1341861/e6577c98-7b49-4274-9bd1-50ddc45450af)
![image](https://github.com/biocompute-objects/playbook-partnership/assets/1341861/27906dea-576f-48f2-ab99-96ee91322358)
