### ISSUE TITLE
Glycan input usecase metanode

### ISSUE THREAD

**Issue by jeet-vora** [biocompute-objects/playbook-partnership#9]
Input - Glycan (human)

Use case 1) Glycan > List of Biosynthesis enzyme glycogenes (applicable to N-linked glycans) > Gene Info

-------------------------------------------------------------------
For usecase: 1 All human N-linked glycans

From glycan details API

For all human N-linked glycans

For glycan part

{
  "glytoucan": {
    "glytoucan_ac": "G17689DH", 
    "glytoucan_url": "https://glytoucan.org/Structures/Glycans/G17689DH"
  }, 

For Human N-linked classification part look for

"species": [
    {
      "common_name": "Human", 
      "taxid": 9606, 
      "name": "Homo sapiens" }

"classification": [
"type": {
        "url": "http://bioportal.bioontology.org/ontologies/GLYCO/?p=classes&conceptid=N-glycan&jump_to_nav=true", 
        "name": "N-linked"
      }

For list of human Biosynthesis enzyme glycogenes look for

  "enzyme": [
    {
      "uniprot_canonical_ac": "Q9H553-1", 
      "gene_link": "https://www.uniprot.org/uniprot/Q9H553", 
      "evidence": [
        {
          "url": "https://data.glygen.org/GLY_000284", 
          "id": "GLY_000284", 
          "database": "GlyGen"
        }
      ], 
      "protein_name": "Alpha-1,3/1,6-mannosyltransferase ALG2", 
      "tax_name": "Homo sapiens", 
      "tax_common_name": "Human", 
      "gene": "ALG2", 
      "tax_id": 9606
    }, 

Note only Homo sapiens proteins canonicals should be extracted

From the uniprot_canonical_ac eg. Q9H553-1., get the gene info from protein details API

Protein Details API

"uniprot": {
    "url": "http://www.uniprot.org/uniprot/P14210-1/", 
    "uniprot_canonical_ac": "P14210-1", 
    "length": 728, 
    "uniprot_id": "HGF_HUMAN"
  }, 
  "gene": [
    {
      "url": "https://www.uniprot.org/uniprot/P14210", 
      "name": "HGF", 
      "locus": {
        "end_pos": 81699008, 
        "strand": "-", 
        "start_pos": 81770438, 
        "chromosome": "7", 
        "evidence": [
          {
            "url": "https://www.ensembl.org/id/ENSG00000019991", 
            "id": "ENSG00000019991", 
            "database": "Ensembl Gene"
          }
        ]
      }
    }
  ], 

Fields for Gene Info
Gene Name - HGF
Chromosome Location - Chromosome 7: 81,699,010-81,770,438 reverse strand

**Comment by HadleyKing** [comment]
FYI: @u8sand
[WIP]
